namespace Notificaciones.Domain.Events;

/// <summary>
/// Immutable domain event contract representing an asynchronous notification to be processed and dispatched by the broker.
/// </summary>
public record NotificationEvent
{
    /// <summary>
    /// Unique tracing tracking identifier for this notification dispatch request.
    /// </summary>
    public Guid NotificationId { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Target email or identifier of the recipient.
    /// </summary>
    public string Recipient { get; init; } = string.Empty;

    /// <summary>
    /// Email address of the sender (especially helpful in contact form messages).
    /// </summary>
    public string SenderEmail { get; init; } = string.Empty;

    /// <summary>
    /// Full name or title of the sender.
    /// </summary>
    public string SenderName { get; init; } = string.Empty;

    /// <summary>
    /// Subject line or summary of the notification.
    /// </summary>
    public string Subject { get; init; } = string.Empty;

    /// <summary>
    /// Raw textual message or formatted payload content.
    /// </summary>
    public string Body { get; init; } = string.Empty;

    /// <summary>
    /// Categorical classification of this event to select appropriate channels and formatting templates.
    /// </summary>
    public NotificationType Type { get; init; } = NotificationType.TestDemo;

    /// <summary>
    /// Priority level (High, Normal, Low) for processing and delivery alerting.
    /// </summary>
    public string Priority { get; init; } = "Normal";

    /// <summary>
    /// Exact UTC timestamp when the notification event was generated by the producer.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Optional dictionary for additional custom metadata (e.g., client IP, user agent, tags).
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();
}